### PR TITLE
Fix missing github_token for release drafter

### PR DESCRIPTION
**Pull request by firstof9**
## Proposed change

- Fix missing github_token for release drafter

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR is related to issue: n/a

### CODE REVIEW

**Comment by firstof9** [comment]
Quick workflow fix

**Review by moralmunky — APPROVED** [review]

**Comment by moralmunky** [comment]
Turn validate back to required?

**Comment by firstof9** [comment]
Nah not yet

**Comment by firstof9** [comment]
Let's keep it off for now till the 0.3 branch then we can set it for the codecov and validate 👍

**Pull request merged**
