### PR TITLE
feat: Added Purolator shipper and Intelcom shipper (used by Amazon Canada) …

### PR DESCRIPTION
**Pull request by glbailey**
…for Canada

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update
- [X] Adds a new shipper
- [ ] Update existing shipper

### CODE REVIEW

**Comment by firstof9** [comment]
You'd actually want to base your changes on the `dev` branch not `master`.

**Comment by glbailey** [comment]
Ah, got it. Thanks for your patience!

Garnet

**Comment by firstof9** [comment]
You'll want to redo the edits from the dev branch, changing it here just causes a mess.

**Comment by glbailey** [comment]
Will do, sorry about that - I wondered about that but didn’t want to create more confusion.

**Comment by glbailey** [comment]
Delete to re-issue PR under dev branch

**Pull request closed without merging**
