### PR TITLE
fix(shippers): Add extra matcher for Canada Post

### PR DESCRIPTION
**Pull request by bbigras**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update
- [ ] Adds a new shipper
- [x] Update existing shipper

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

### CODE REVIEW

**Comment by firstof9** [comment]
They added an extra domain name?

**Comment by bbigras** [comment]
I don't see any email in my gmail account with "donotreply@canadapost.postescanada.ca". I only have some with the new one.

Maybe the address is different for me since I'm in Québec.

**Comment by bbigras** [comment]
Note that the PR has some extra commits now. Maybe a rebase is needed.

**Comment by firstof9** [comment]
Ya they occurred when I changed the base branch, not a problem tho.

**Comment by bbigras** [comment]
Thanks!

**Pull request merged**
