### PR TITLE
feat: add amazon otp sensor

### LINKED ISSUE #896: [Feature Request] Support for an Amazon one time password sensor.
**Is your feature request related to a problem? Please describe.**
Amazon has started requiring that delivery drivers need to be given a one time password for certain more expensive orders. Even though I have a package delivery box that they use 95% of the time now (finally), certain orders still require the one time password. I've had to have a few deliveries redelivered due to not being able to give them the code when I'm away. Amazon says you need to give the code in person, but the drivers don't care. So I've been putting the code on the screen on my doorbell and directing them that the code is there with a TTS notification, and it works great. It would be nice if the integration could grab this code and store it as a sensor so it can automatically update my doorbell.

Here is an example of the email with the one time password:
CleanShot 2024-05-30 at 20 21 48@2x

I suppose there could be times where you have more than one delivery requiring a one time password in a day, so putting them all in the same sensor, or having individual sensors could work.

Thanks!

### PR DESCRIPTION
**Pull request by firstof9**
## Proposed change

Add Amazon OTP sensor

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update
- [ ] Adds a new shipper
- [ ] Update existing shipper

## Additional information

- This PR fixes or closes issue: fixes #896

### CODE REVIEW

**Comment by Bluscream** [comment]
Why is this not merged lol?

**Comment by firstof9** [comment]
Sample emails are needed for tests.

**Comment by Bluscream** [comment]
I see, thanks!

**Comment by snickers2k** [comment]
> Sample emails are needed for tests.

you still need sample emails? because i think they don't really change at all?

**Comment by firstof9** [comment]
> you still need sample emails? because i think they don't really change at all?

Yes, if you have one.

**Comment by Bluscream** [comment]
give me a mail address and i will forward some

**Comment by firstof9** [comment]
Well that didn't go as planned. This will be in a new PR.

**Comment by firstof9** [comment]
Please see #1037

**Pull request closed without merging**
