### PR TITLE
Efficiency patch

### LINKED ISSUE #5: -1 Packages in transit
In Transit shows -1 after deliveries are completed due to a new UPS subject line.

The new, additional, UPS subject line for a package out for delivery that you can view the status on a live map, "UPS Update: Follow Your Delivery on a Live Map".

### LINKED ISSUE #10: Slow start warnings
The component begins checking for email right away and appears to be causing a slowdown loading other components causing warnings.

### LINKED ISSUE #14: Each sensor logs into mailbox repeatedly

### LINKED ISSUE #32: Mail gif assumes shape of first mail piece
The mail I received today started with a square image and all subsequent rectangular images filled canvas area cutting off the left and right side. 

I had solved for this previously by resizing all the images proportionately within 700x315. I think this matched the no mail image. When assembling the gif the background was filled with white so you wouldn't see the outside parts of the pervious image if it was larger than the new image.

For reference:
`IMG_RESIZE_OPTIONS = ('convert -resize 700x315 ')
GIF_MAKER_OPTIONS = ('convert -delay 300 -loop 0 -coalesce -fill white '
                     '-dispose Background ')`

### LINKED ISSUE #33: GIF rotation is very slow
I find that 10 seconds is very slow rotation speed, especially if you have few mail pieces come through. It could be nice to add and option to adjust this speed when setting up the integration.

### LINKED ISSUE #34: Not picking up FedEx package as in transit
V0.07, installed via HACS using latest version of documentation
HomeAssistant version - 0.105.3

Got an email notification from FedEx from trackingupdates@fedex.com with title:

**FedEx Shipment 45280775XXXX: Your package is on its way** 
(Number redacted, but if you need it give me a way to DM you.)

But no state change on sensor.packages_in_transit or sensor.mail_fedex_packages.  

Link to email (address/package number redacted): https://drive.google.com/file/d/1foXa0mYWvv71c2C_vMgr256dzyXCt3YG/view?usp=sharing

Expected behavior:  Sensors would increase from 0 to 1 in at least packages in transit.

### LINKED ISSUE #36: In transit shows the same amount after deliveries recorded
Today I received 2 in delivering today messages and 2 delivered messages from USPS. I would expect the delivering count to reduce as the delivered count increased and the total USPS package count to only be 2 packages.

mailcard

### PR DESCRIPTION
**Pull request by firstof9**
* Only login to email once and pull all the emails needed in one swoop - Fixes #14 
* Changed GIF rotation time to 5 seconds - Fixes #33 
* Subtract delivered packages from 'in transit' packages, should no longer result in negative counts - Fixes #5 and Fixes #36 
* No more slow start warnings since we check the email in one call now - Fixes #10 
* Added aspect ratio calculations to keep image looking correctly - Fixes #32 
* Added additional subject searches for FedEx emails - Fixes #34 
* Bump version to 0.1.0 since we're no longer using Imagemagick and fixed the speed issues, seemed like a good milestone.

### CODE REVIEW

**Comment by firstof9** [comment]
I've been running this for the past 3-4 days, other than the aspect ratio bit which I haven't been able to confirm yet, all else works great.

**Comment by moralmunky** [comment]
FYI, I just add `today = '18-Feb-2020'`after line 901 in the sensor.py to pull a previous emails to test.

I had issues again with starting due to Mail Attachment.txt being added in the image array. I added the file name to line 828 in the sensor.py to the items to remove from the image array before processing.
`remove_terms = ['mailerProvidedImage', 'ra_0' , 'Mail Attachment.txt']` 

The image rotation continues to be an issue. I think the is a limitation with file camera. My observation is that there are only 10 seconds to get through all the mail images before it reloads the file. I don't think I ever encountered that before since I embedded the imagine the custom card instead of using the camera component.

So, my 4 mail images at 5 seconds each only gets through 2 images.
If I set the duration to 10, I only ever see 1 image. Not sure what the fix is here for a good viewing speed and being able to show the user all mail images.

For image resizing, doesn't seem to be there. I thought that maybe rescale is what should be used by I couldn't get the results. I think you would have to evaluate images widths and height because either could be out of the 317 x 700 perimeter. I'll keep looking into this.

**Comment by firstof9** [comment]
> The image rotation continues to be an issue. I think the is a limitation with file camera. My observation is that there are only 10 seconds to get through all the mail images before it reloads the file. I don't think I ever encountered that before since I embedded the imagine the custom card instead of using the camera component.

Setting the lovelace card to "live" resolved this for me.

**Comment by firstof9** [comment]
> For image resizing, doesn't seem to be there yet. I thought that maybe rescale is what should be used but I couldn't get the right results either. I think you would have to evaluate images widths and height because either could be out of the 317 x 700 parameter. I'll keep looking into this.

The resize function isn't working for you then? Or should I have it resize the width too?
```
# Resize images
# This should keep the aspect ratio of the images
#################################################


def resize_images(images):
    sized_images = []
    for image in images:
        if image.shape[1] < 700:
            wpercent = 700/image.shape[1]
            height = int(float(image.shape[0])*float(wpercent))
            sized_images.append(img_as_ubyte(resize(image, (height, 700))))
        else:
            sized_images.append(img_as_ubyte(resize(image, (317, 700))))

    return sized_images
```

**Comment by moralmunky** [comment]
> Setting the lovelace card to "live" resolved this for me.

I see, you put in a picture entity card and that has the live setting. If this is the case we should probably make a note of the issue with a regular entity and change the 3 recommended configuration in the documentation to use the this card with the live settings on.

**Comment by moralmunky** [comment]
Today I am getting the message that the image-no-mailpieces700.jpg doesn't exist inside the www path. I thought I read that the component now populates that folder? 

The image sizing is currently evaluating if the image width is less than 700. The intended function should be if the image width is greater than 700 do something. Even after scaling down the width, it is possible for the image height to still be too large for the intended canvas size. Also there is a type for the height, to match the no image for mail file the size 315px instead of 317.

**The logic**
From original image array, If image height is greater than 315
          get new width, make image 315 x new width
         add to first_pass_images array
else
         add unmodified image to first_pass_images array

From first_pass_images array, If image width is greater than 700
        get new height, make image new height x 700
       add to sized_images array
else
       add unmodified image to sized_images array

This is getting there. When stitching together in the gif, my first image was resized to w:660h:315 and that becomes the size of the gif. 

Two options I can think of now:
1. Find how skimage can add blank pixels to make all the images exactly 315 x 700 after they are sized to fit within that size.
2. Add a template image that is 315 x 700 to always be the first image of the array so the gif always takes on the right size. It could say 'mail today' or something so it's not just a blank slide.

`# Resize images
# This should keep the aspect ratio of the images
#################################################


def resize_images(images):
    first_pass_images = []
    sized_images = []
    for image in images:
        #1 height
        if image.shape[0] > 315:
            shape = "w:" + str(image.shape[1]) + "h:" + str(image.shape[0])
            wpercent = 315/image.shape[0]
            width = int(float(image.shape[1])*float(wpercent))
            size = "w:" + str(width) + "h:315"
            first_pass_images.append(img_as_ubyte(resize(image, (315, width))))
            _LOGGER.debug("Image size: %s", str(shape))
            _LOGGER.debug("Image too tall, new width: %s", str(width))
            _LOGGER.debug("resize percent: %s", str(wpercent))
            _LOGGER.debug("new size: %s", str(size))
        else:
            first_pass_images.append(image)
            _LOGGER.debug("Image fine")
            
    for image in first_pass_images:
        #1 check hegh
        if image.shape[1] > 700:
            shape = "w:" + str(image.shape[1]) + "h:" + str(image.shape[0])
            wpercent = 700/image.shape[1]
            height = int(float(image.shape[0])*float(wpercent))
            size = "w:700" + "h:" + str(height)
            sized_images.append(img_as_ubyte(resize(image, (height, 300))))
            _LOGGER.debug("Image size: %s", str(shape))
            _LOGGER.debug("Image too wide, new height: %s", str(height))
            _LOGGER.debug("resize percent: %s", str(wpercent))
            _LOGGER.debug("new size: %s", str(size))
        else:
            sized_images.append(image)
            _LOGGER.debug("Image fine")

    return sized_images`

**Comment by moralmunky** [comment]
In my goosing I did find this, using a different library.
https://jdhao.github.io/2017/11/06/resize-image-to-square-with-padding/

**Comment by moralmunky** [comment]
I'm going to merge this, add in the additional remove term, and add in the information for the camera card needing to be 'live' to the readme.

I think that would be good for a new release and the continue to work on the image sizing.

**Pull request merged**
