### PR TITLE
0.2.2 - Release

### LINKED ISSUE #163: ISSUE: Re-configuring integration after update not allowing "Submit"
**Describe the bug**
Was on 0.2.0 previous to the update and everything was working.  Updated to 0.2.1 and followed the instructions by reconfiguring the integration.  Clicking 'Submit' produces nothing and doesn't save settings.  Removed from HACS, rebooted, added from HACS, rebooted, tried configuring and same issue.  Tried downgrading to 0.2.0 and still same issue, what gives?  Tried checking/unchecking and hitting submit for "random" checkbox and "mp4" as well.

**Environment (please complete the following information):**
 - OS: Raspbian
 - Type of device: Rpi4 4GB
 - Home Assistant version: 111.4
 - Hassio/Docker/Core? Core
 - Component version: 0.2.1

**Logs**
Nothing in logs, not sure if this is related?

`domain.duckdns.org/frontend_latest/app.cb642fbe.js:1188:3031 Uncaught TypeError: Cannot read property 'length' of null`

**Screenshots**
N/A
image

**Additional context**
N/A

### LINKED ISSUE #190: ISSUE: Delviering Count
**Describe the bug**
For one package that is delivering then delivered, expecting in transit to reduce to 0 after delivery. sensor.mail_usps_packages, sensor.mail_packages_in_transit, sensor.mail_usps_delivering show unexpected numbers.

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
```
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Item Delivered
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for auto-reply@usps.com with subject 1 Item Delivered results: b'284'
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Sensor: usps_delivering
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Expected Delivery on
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Your item is out for delivery in 3 emails
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Debug: 1
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found Your item is out for delivery in email matches: 1
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for auto-reply@usps.com with subject 1 Expected Delivery on results: b'282'
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for tracking numbers for usps
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] No tracking number found for usps
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Info: {'count': 2, 'tracking': []}
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] info[ATTR_COUNT]: 2
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Delivered: 1
2020-07-25 23:19:56 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] total: 1
```

**Screenshots**
3 USPS Emails today. 1  Informed Delivery, 1 Expected Delivery, and 1 Delivered

Screen Shot 2020-07-25 at 10 49 14 PM

**Additional context**
Sensor | Count
--- | ---
 sensor.mail_packages_delivered	|1
 sensor.mail_packages_in_transit	|1
 sensor.mail_updated	|Jul-25-2020 11:01 PM
 sensor.mail_usps_delivered	|1
 sensor.mail_usps_delivering	|1
 sensor.mail_usps_mail	|1
 sensor.mail_usps_packages	|2

### LINKED ISSUE #194: ISSUE: Error setting up integration
**Describe the bug**
 Error while setting up mail_and_packages platform for sensor

**Environment (please complete the following information):**

Tried v0.2.1-1 and v0.2.2-b13

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.19.0-5-amd64
python_version | 3.8.3
timezone | America/New_York
version | 0.113.2
virtualenv | false

**Logs**
```

2020-07-29 10:30:52 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mail_and_packages
2020-07-29 10:30:52 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Config scan interval: 0:05:00
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Informed Delivery mail
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Cleaning up image directory: /config/mail_and_packages/
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Informed Delivery email found processing...
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Extracting image from email
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing duplicate images.
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing USPS announcement images.
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Image Count: 1
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Resizing images to 724x320...
2020-07-29 10:30:53 ERROR (MainThread) [custom_components.mail_and_packages.sensor] Error attempting to read image /config/mail_and_packages/ATT00001.txt: cannot identify image file <_io.BufferedReader name='/config/mail_and_packages/ATT00001.txt'>
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Creating array of image files...
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Generating animated GIF
2020-07-29 10:30:53 ERROR (MainThread) [custom_components.mail_and_packages.sensor] Error attempting to generate image: Zero images were written.
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Item Delivered
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for auto-reply@usps.com with subject 1 Item Delivered results: b''
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Expected Delivery on
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for out for delivery in emails
2020-07-29 10:30:53 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)


  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for


    return fut.result()


  File "/config/custom_components/mail_and_packages/sensor.py", line 137, in async_setup_entry


    sensors.append(PackagesSensor(data, variable))


  File "/config/custom_components/mail_and_packages/sensor.py", line 268, in __init__


    self.update()


  File "/config/custom_components/mail_and_packages/sensor.py", line 316, in update


    self.data.update()


  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper


    result = method(*args, **kwargs)


  File "/config/custom_components/mail_and_packages/sensor.py", line 212, in update


    total = int(get_count(account, sensor)) - data["usps_delivered"]


  File "/config/custom_components/mail_and_packages/sensor.py", line 635, in get_count


    count += find_text(data[0], account, filter_text)


  File "/config/custom_components/mail_and_packages/sensor.py", line 685, in find_text


    email_msg = email_msg.decode("utf-8")


UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 2573: invalid start byte

```

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

### LINKED ISSUE #220: ISSUE: Unable to set up multiple instances if both are same email provider
**Describe the bug**
Trying to create two Amazon sensors from sperate accounts to eventually combine into one sensor but only allows for one or the other. When adding sensors from the new account, the same sensors from the old account are completely removed and replaced instead of keeping both with different names. 

**Logs**
Platform mail_and_packages does not generate unique IDs. ID imap.gmail.com_Mail Amazon Packages already exists - ignoring sensor.mail_amazon_packages
Platform mail_and_packages does not generate unique IDs. ID imap.gmail.com_Mail Amazon Packages Delivered already exists - ignoring sensor.mail_amazon_packages_delivered
Platform mail_and_packages does not generate unique IDs. ID imap.gmail.com_Mail Amazon Hub Packages already exists - ignoring sensor.mail_amazon_hub_packages

**Additional context**
The emails are sent to two separate accounts, but both are Gmail.

### PR DESCRIPTION
**Pull request by firstof9**
## Breaking change

* Add option to disable sensors
* 2 sensors renamed
* Support for forwarded Amazon emails (requires reconfiguration)
* Due to more unique ids being generated, old sensors will need to be removed and renamed.

## Proposed change

- Add tracking numbers as attributes to 'delivering' sensors
- Add DHL Sensors
- Condensed sensor update function (less elif statments)
- Condensed const import
- Fix missing error message string
- Adjust config_flow to only check for ffmpeg if MP4 enabled
- Fixes #163
- Automatic detection of Home Assistant configuration directory added to config_flow
- Actually disable sensors that are disabled and do not attempt to check them still
- Add Amazon Delivered Sensor
- Amazon delivered image now downloads into the image directory
- Internationalize Amazon delivered search and image download
- Fix USPS email counting error
- Add error catch for USPS informed delivery emails with attachments. Should fix #194
- Fix #190
- Update USPS Tracking number regex
- Filter duplicate notification emails via tracking numbers fixes #92
- Fix order number logic for Amazon sensor
- Fix non-multipart forwarded Amazon delivered emails not processing properly when pulling the image
- Support for UPS multi delivered emails
- Add 2 loops to generated mp4
- Add extra debugging messages
- Amazon Canada fix
- FedEx Canada fix
- Handle Amazon Hub emails
- Parse combo from subject line and populate as sensor attribute
- Better unique_ids for sensors - fixes #220
- Fix FedEx package sensor for real #221
- Fix Amazon sensor not working #225
- Fix Amazon Hub sensor #206
- Potential fix for Amazon sensor not processing emails #225
- Update DHL from email address #164
- DHL Subjects were swapped #164
- Update USPS Informed Delivery email address
- Guard against sensors not loaded in correct order
- USPS changed the subjects on emails

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

### CODE REVIEW

**Comment by firstof9** [comment]
@moralmunky I think we're good for a 0.2.2 release what do you think?

**Comment by moralmunky** [comment]
Thought I would finally set up amazon forwarding address to test this. I'm not able to get it to pick up. I see the magic should be happening in sensor.py line 929 935. I only see it looking for the standard amazon from emails in the log. Thoughts?

Integration Settings:
All amazon sensors are checked
Amazon forwarded email address: christopher@moralmunky.com

Email Subject:
`Fwd: Your Amazon.com order #113-1309919-7779465 has shipped`

Email contents:
```
Begin forwarded message:

From: "Amazon.com" <shipment-tracking@amazon.com>
Subject: Your Amazon.com order #113-1309919-7779465 has shipped
Date: November 26, 2020 at 11:43:19 AM EST
To: christopher@moralmunky.com
Reply-To: no-reply@amazon.com

Hi Christopher, your package will arrive: Saturday, November 28
This contains items from 2 orders
```

Amazon log section

```
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for (['TrackingUpdates@fedex.com', 'fedexcanada@fedex.com']) with subject 2 (Your package is scheduled for delivery today) results: b'' count: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: shipment-tracking@amazon.com
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: shipment-tracking@amazon.ca
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: shipment-tracking@amazon.co.uk
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: shipment-tracking@amazon.in
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon Count: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: shipment-tracking@amazon.com
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: shipment-tracking@amazon.ca
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: shipment-tracking@amazon.co.uk
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: shipment-tracking@amazon.in
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon order: []
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon delivered email(s)...
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: order-update@amazon.com
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon delivered email(s) found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon image in emails...
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] HTML Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: order-update@amazon.ca
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon delivered email(s) found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon image in emails...
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] HTML Amazon emails found: 0
2020-11-28 15:30:30 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: order-update@amazon.co.uk
2020-11-28 15:30:31 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon delivered email(s) found: 0
2020-11-28 15:30:31 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon image in emails...
2020-11-28 15:30:31 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] HTML Amazon emails found: 0
2020-11-28 15:30:31 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Checking for Amazon email address: order-update@amazon.in
2020-11-28 15:30:31 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon delivered email(s) found: 0
2020-11-28 15:30:31 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon image in emails...
2020-11-28 15:30:31 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] HTML Amazon emails found: 0
2020-11-28 15:30:31 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon hub emails found: 0

```

**Comment by firstof9** [comment]
That latest commit should give more debugging on what's going on with the forwards, and I adjusted the if statement. See if that helps.

I utilize gmail forwards so the emails arrive just as they would if I was the intended recipient so I can't really test these.

**Comment by firstof9** [comment]
If you pass me the raw email @moralmunky I can devise a test in the 0.3.0 branch which will help me figure this out too 👍

**Comment by moralmunky** [comment]
> That latest commit should give more debugging on what's going on with the forwards, and I adjusted the if statement. See if that helps.
> 
> I utilize gmail forwards so the emails arrive just as they would if I was the intended recipient so I can't really test these.

`Amazon forward addresses: None`

The input doesn't appear to be passed into the function. Do you want to debug this now or release and debug after?

**Comment by firstof9** [comment]
We can debug after, I don't think as many people use this feature as we think.

**Review by moralmunky — APPROVED** [review]

**Comment by firstof9** [comment]
Guess we should remove the require on validate so we can merge 😛

**Review by moralmunky — APPROVED** [review]

**Comment by moralmunky** [comment]
What needs to be done?

**Comment by firstof9** [comment]
Remove the "Branch protection rules" under Settings -> Branches

**Comment by firstof9** [comment]
Well specifically the disable this one:
image

The require review you can leave on.

**Pull request merged**
