### PR TITLE
Images for picture elements card

### PR DESCRIPTION
**Pull request by ReenigneArcher**
## Proposed change

Adding files for custom picture elements card. This allows to clean-up the appearance of USPS scanned mail items. There is a white background to account for low quality scans. The airmail overlay from the mail_none.gif was made transparent and overlays the camera image. Additionally there is a vignette effect to darken the corners of the camera.

Here is an example yaml for the custom card. (Modify if no vignette effect is desired.)
```
type: picture-elements
elements:
  - type: image
    entity: null
    camera_image: camera.mail_usps
    camera_view: live
    style:
      top: 50%
      left: 50%
      width: 100%
  - type: image
    entity: null
    image: local/mail_and_packages/overlay.png
    style:
      top: 50%
      left: 50%
      width: 100%
  - type: image
    entity: camera.mail_usps
    image: local/mail_and_packages/vignette.png
    style:
      top: 50%
      left: 50%
      width: 100%
image: local/mail_and_packages/white.png
entity: camera.mail_usps
tap_action:
  action: more_info
hold_action:
  action: none
```

And screenshots.

no mail w/ vignette
image

mail w/ vignette
image

mail w/o vignette
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

### CODE REVIEW

**Review by firstof9 — CHANGES_REQUESTED** [review]
Please move the files to the `custom_components/mail_and_packages/` directory, and we'll have them copied over to the `www` directory.

**Comment by ReenigneArcher** [comment]
> 
> 
> Please move the files to the `custom_components/mail_and_packages/` directory, and we'll have them copied over to the `www` directory.

Okay... shoot I had them there initially but couldn't get HA to use images in that location on the card. Looks like images can only be moved using the command line. I'll have to figure that out as I've not used it before for git.

**Comment by firstof9** [comment]
> I had them there initially but couldn't get HA to use images in that location on the card.

Correct, we'll need to make a function to copy them into the "image output path".

**Comment by firstof9** [comment]
Would you like me to do the python part?

**Comment by ReenigneArcher** [comment]
> 
> 
> Would you like me to do the python part?

If you don't mind. My python experience is fairly limited. Otherwise I can try to figure it out. Thanks!

**Review by firstof9 — APPROVED** [review]

**Review by firstof9 — CHANGES_REQUESTED** [review]
One last change, please change the branch to 0.2.0

**Comment by firstof9** [comment]
Oops nevermind I was able to.

**Review by firstof9 — APPROVED** [review]

**Comment by firstof9** [comment]
Actually will put this into 0.3.0 branch 👍

**Pull request merged**
