### PR TITLE
fix(shipper): Updated subject for FedEx sensors.

### PR DESCRIPTION
**Pull request by skewll**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update
- [ ] Adds a new shipper
- [x] Update existing shipper

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

### CODE REVIEW

**Comment by skewll** [comment]
Not sure what went wrong..

**Comment by firstof9** [comment]
The test fail isn't a result of your PR, don't worry.

**Comment by skewll** [comment]
Good to know! Thanks.

**Comment by skewll** [comment]
So what are the next steps?

**Comment by firstof9** [comment]
Sorry, I forgot to push the button the other day.

**Pull request merged**
