### PR TITLE
fix(shipper): add dhl more address

### PR DESCRIPTION
**Pull request by Jaharmi**
## Proposed change

Add criteria for DHL shipments. Repeat of #735 after rebasing from “dev” branch.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update
- [ ] Adds a new shipper
- [X] Update existing shipper

## Additional information

This PR fixes issue: https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/727

### CODE REVIEW

**Comment by Jaharmi** [comment]
If this is accepted, can it have the HACKTOBERFEST-ACCEPTED label added? I’d like to get credit for [Hacktoberfest 2023](https://hacktoberfest.com/participation/). Thanks!

**Comment by firstof9** [comment]
Looks like you need to run `black` and it should pass tests.

**Comment by Jaharmi** [comment]
Formatted with Black.

**Comment by firstof9** [comment]
Thanks!

**Comment by firstof9** [comment]
Let me know if that counted for hacktoberfest.

**Pull request merged**
